apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.in-memory
  version: v1
  metadata:
    - name: connectionString
      value: "memory://"
  # For production, use rmbrain-pubsub (Redis) component instead

