apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rmbrain-statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6379"
    - name: redisPassword
      value: ""
    - name: enableTLS
      value: "false"
  # Production-ready Redis state store component
  # Update redisHost and redisPassword for production environments

