apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.in-memory
  version: v1
  metadata:
    - name: connectionString
      value: ""
  # For production, use rmbrain-statestore (Redis) component instead

